apiVersion: v1
data:
  mapRoles: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-27T17:03:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "174153"
  uid: 0732d67f-2443-4437-aa48-8fd126fdc5e5
